const express = require('express')
const router = express.Router()

const price = require('../controllers/flights/common/price.controllers')
const validateClient = require('../validateClient/index')
const fareCalendar = require('../controllers/flights/common/fareCalendar.controllers')
const sendEticketEmail = require('../controllers/flights/common/sendEticketEmail.controllers')
const void_ = require('../controllers/flights/common/void.controllers')
const book = require('../controllers/flights/common/book.controllers')
const cancel = require('../controllers/flights/common/cancel.controllers')
const bookings = require('../controllers/flights/common/bookings.controllers')
const v2 = require('../controllers/flights/common/v2.controllers')

router.get('/v2/logs', validateClient, v2.logsdetailsv2)
router.get('/bookings', validateClient, bookings.getallbookings)
router.get('/bookings/:id', validateClient, bookings.getbookingsbyid)
router.patch('/bookings/:id', validateClient, bookings.updatebooking)
router.post('/cancel/:tavaBookingId', cancel.cancel)
router.post('/book', validateClient, book.book)
router.post('/void/:tavabookingid', void_.void_)
router.get('/v2/book-callback', validateClient, v2.bookcallback_v2)
router.post('/sendEticketEmail', sendEticketEmail.sendeticketemail)
router.post('/fare-calendar', validateClient, fareCalendar.fareCalendar)
router.post('/price', validateClient, price.price)
module.exports = router
