const express = require('express')
const router = express.Router()
const validateClient = require('../validateClient/index')
const refund = require('../controllers/flights/common/refund.controllers')
const payment = require('../controllers/infrastructure/payment/payment.controllers')
const getPaymentDetails = require('../controllers/infrastructure/payment/getPaymentDetails.controllers')
const paymentRule = require('../controllers/flights/common/paymentRule.controllers')
const logs = require('../controllers/infrastructure/logging/logs.controllers')
const promocodes = require('../controllers/infrastructure/promocodes/promocodes.controllers')
const sendMail = require('../controllers/infrastructure/send_mail.controllers')
const sendOtp = require('../controllers/infrastructure/idp/send_otp.controllers')
const submit_query = require('../controllers/infrastructure/submit_query.controllers')
const session = require('../controllers/infrastructure/session/session.controller')

router.post('/submit-query', submit_query.submitqueries)
router.post('/send-otp', sendOtp.sendotp)
router.post('/send-mail', sendMail.sendmail)
router.get('/promocodes', promocodes.getpromocodes)
router.patch('/promocodes/:id', promocodes.updatepromocode)
router.get('/logs', validateClient, logs.logsdetails)
router.delete('/paymentRule/:id', paymentRule.deletepaymentrule)
router.post('/payment', payment.payment)
router.post('/refund/:paymentId', refund.refund)
router.post('/session', session.sessioncreate)
router.delete('/session/:id', session.sessiondelete)
router.get('/session/:id', session.sessionfetch)
router.patch('/session/:id', session.sessionupdate)
router.get('/getPaymentDetails', getPaymentDetails.getPaymentDetails)

module.exports = router
